### ISSUE TITLE
Line syntax error.

### ISSUE THREAD

**Issue by torytyler** [leon0410898/OC-XPS13-9300#1]
https://github.com/leon0410898/XPS13-9300-hackintosh/blob/e537187f0d109979ba2f16c9310e705445b011d1/EFI/OC/config.plist#L925

config won't run on a fresh catalina USB, culrpit can be tracked back to incomplete syntax on line 925. :)

**Comment by torytyler** [comment]
confirming that after fixing this line the USB boots fine to macOS recovery.

**Comment by leon0410898** [comment]
thanks to point out the error
