### ISSUE TITLE
Is the sleep mode fully functional?

### ISSUE THREAD

**Issue by Yefee** [leon0410898/OC-XPS13-9300#12]
Hi, 

Thanks for creating this great repo!
I am wondering if the sleep mode is fully functional. The Chinese md says after one sleep, the machine automatically reboots, while I didn't find similar descriptions in the English md.

Thank you!

**Comment by leon0410898** [comment]
您好,中文已經更新了.s3睡眠是正常的,有任何問題歡迎提出,謝謝!
(中文readme比較舊了,建議還是以英文為主,後續有時間會在更新中文)

**Comment by Yefee** [comment]
Thank you!
May I ask if there are any instructions on how to install Hackintosh on XPS9300? It seems to me only configs are included in this repo.

**Comment by leon0410898** [comment]
https://dortania.github.io/OpenCore-Install-Guide/

**Comment by Yefee** [comment]
Thank you!
