### ISSUE TITLE
i7 - 1065G7-UHD(4k) 

### ISSUE THREAD

**Issue by bohenao** [leon0410898/OC-XPS13-9300#13]
New installation,
Halt on : IOConsoleUsers: gIOscreenLockState 3, .....
Screen dimmed for 5 sec and then restarted.
![20201110_152013](https://user-images.githubusercontent.com/26623937/98633819-4f640480-2376-11eb-9347-8c550412ccde.jpg)

**Comment by bohenao** [comment]
Installation resolved:

boot arg : -igfxvesa
PciRoot(0x0)/Pci(0x2,0x0) replaced with the attached picture
<img width="973" alt="Screen Shot 2020-11-10 at 9 47 40 pm" src="https://user-images.githubusercontent.com/26623937/98664481-8a7a2e00-239e-11eb-9865-f4582fffbd3a.png">

**Comment by little2b** [comment]
Hi,have you installed macos successfully ?And how about the daily experience ?
