### ISSUE TITLE
How to boot

### ISSUE THREAD

**Issue by lekrsu** [leon0410898/OC-XPS13-9300#14]
New to core boot. How do I even get the USB to boot the system? Tried having a FAT32 usb with the recovery files for big sur, and the efi from this GitHub; but it doesn't boot correctly.

**Comment by leon0410898** [comment]
This may help you.
https://dortania.github.io/OpenCore-Install-Guide/

**Comment by jhonmaker-gonsu** [comment]
I followed  these steps,but I can't boot currectly making my USB bootable with command on terminal. And I mounted EFI ,copied "big sur boot EFI”and paste it to the EFI volume. I set BIOS setting according to your readme .then I try to boot with the USB, I got kernel panic. Am I missing any steps? 
[opencore-2020-07-07-014143.txt](https://github.com/leon0410898/XPS13-9300-hackintosh/files/5683744/opencore-2020-07-07-014143.txt)
![ファイル_000](https://user-images.githubusercontent.com/75864042/101994723-cee34b80-3d07-11eb-9c2e-5cf7e449b936.jpeg)

**Comment by bohenao** [comment]
I resolved this problem by updating opencore to version 0.63.

**Comment by jhonmaker-gonsu** [comment]
> I resolved this problem by updating opencore to version 0.63.

Thanks for the advice!
I update opencore,But I get the same error.
My BIOS is 1.1.0,dose it make this error?

**Comment by jhonmaker-gonsu** [comment]
Or Am I taking wrong steps for updating?
I think I followed this site[https://dortania.github.io/OpenCore-Post-Install/universal/update.html#updating-opencore](url)
But I  could make a mistake on  config.plist phase.
All I do on this process is add missing values to my config.plist right?

**Comment by jhonmaker-gonsu** [comment]
I'm still on the same issue. Did you change something other than provided BIOS setting?
