### ISSUE TITLE
安装界面自动重启

### ISSUE THREAD

**Issue by qibinghua** [leon0410898/OC-XPS13-9300#2]
我是9300 2 in one的机器

**Comment by leon0410898** [comment]
有沒有筆記本型號連結？不清楚你的硬件設備.另外,最好能提供報錯信息,否則很難判斷問題出哪

**Comment by qibinghua** [comment]
https://www.dell.com/zh-cn/shop/%E4%BA%8C%E5%90%88%E4%B8%80%E6%9C%AC/xps-13-%E4%BA%8C%E5%90%88%E4%B8%80%E7%AC%94%E8%AE%B0%E6%9C%AC/spd/xps-13-9310-2-in-1-laptop

但是是9300系列的, 10代U

**Comment by leon0410898** [comment]
連結裡顯示11代cpu,11代目前無解

**Comment by qibinghua** [comment]
我的那个机器是10代的U的

**Comment by leon0410898** [comment]
加QQ吧,這樣問太沒效率

**Comment by leon0410898** [comment]
2377348376

**Comment by little2b** [comment]
大佬可以给个qq吗
