### ISSUE TITLE
potential TB3 Hotplug fix?

### ISSUE THREAD

**Issue by uzair-io** [leon0410898/OC-XPS13-9300#22]
I was reading online and found some resources of getting tb3 to work with hotplug on dell laptops and came across this https://github.com/xxxzc/xps15-9570-macos/issues/40#issuecomment-750740537, is it possible to implement this for our dell XPS?

**Comment by uzair-io** [comment]
This kext
https://github.com/the-darkvoid/macOS-IOElectrify

Enables the TB3 controller on boot so we don’t need a TB3 device always plugged in.

**Comment by cowpod** [comment]
IOElectrify.kext and TbtForcePower.efi driver are enough to get hotplug working, but hotUnPlug doesn't work. 
For my Rx580, I get Radeon 5000/6000 PCI disconnect spam in logs. You may need to patch out XTBT's call to self, which I haven't tried.

**Comment by uzair-io** [comment]
Interesting...

**Comment by cowpod** [comment]
So I've checked - you need IOElectrify.kext, and a new SSDT in order to provide PCI0.TRP0.PXSX.BRDG and PCI0.TRP2.PXSX.BRDG. I haven't gotten it to work correctly, but I got close by dropping TcssSsdt and injecting a patched version with the new devices
.
