### ISSUE TITLE
Mac partition not recognized 

### ISSUE THREAD

**Issue by wzygadlo** [leon0410898/OC-XPS13-9300#7]
First of all, I would like to thank you for your work and time 👍.

I did update my local EFI folder with the latest commit for none4k/BigSur, but now OpenCore does not see my AFPS partition only two options available. 

BTW I am running Catalina

```
1. OpenShell.efi
2. Reset NVRAM
```

Based on logs, looks like something is missing in <PlatformInfo> 
` Missing key CustomMemory.` 

![IMG_0153](https://user-images.githubusercontent.com/26280326/97496835-d2bd3900-1926-11eb-9708-53d79653ba62.jpg)

I literally use your config.plist no changes there as for now. I would appreciate your help.

**Comment by leon0410898** [comment]
Hi, i didn't see anything wrong in the picture. 
" OpenCore does not see my APFS partition" You mean you can't see any boot options in your opencore bootloader?

**Comment by wzygadlo** [comment]
Pretty much, I see only this 


![IMG_0154](https://user-images.githubusercontent.com/26280326/97503023-80cde080-1931-11eb-9f58-1add3e78b9c0.jpg)

**Comment by leon0410898** [comment]
Have you followed the [Dortania Guide](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#grabbing-the-installer) to create the installer?

**Comment by wzygadlo** [comment]
Yes I did follow OpenCore guide, this is from my local SSD disk, but when I copied over latest commit to USB I got this 

![IMG_0155](https://user-images.githubusercontent.com/26280326/97508163-2d14c480-193c-11eb-8de1-e8389a30df88.jpg)

![IMG_0156](https://user-images.githubusercontent.com/26280326/97508161-2be39780-193c-11eb-8b6e-f4f79db88ea3.jpg)

SecurityBoot is disabled etc.. 

so the commit from 18days ago works perfectly fine

**Comment by leon0410898** [comment]
change securebootmodel to j230k(air), j214k(pro), ApECID set to 0

**Comment by wzygadlo** [comment]
It does work 👍 🥇 Thank you
