### ISSUE TITLE
Problem with installation 

### ISSUE THREAD

**Issue by psanikos** [leon0410898/OC-XPS13-9300#8]
Hi I used the guide before and I installed catalina perfectly then I tried before the update to this guide to install big sur which didn't go well . Now I created again an installer with catalina and opencore 0.62 I used the efi file provided and I tried to reinstall catalina but now the installer says that the recovery server could not be contacted even though the WiFi is working ... Any ideas ;

**Comment by leon0410898** [comment]
Can you provide more information about the problem when you install Big Sir?

**Comment by psanikos** [comment]
I haven't tried with the provided efi yet . I just tried to do an update from within catalina with big sur update  beta 7 that I had saved on a disk and the update succeeded but the WiFi didn't work. Then I saw the updated instructions here and I decided to start from the beginning to be sure . So I used gibmacos from windows and created a recovery usb , then I copied your efi folder and started the installation . I formated the whole drive to apfs and when I pressed reinstall mac os I had the error. As a not the laptop connects automatically to my wifi I used the safari on recovery to check if it connects to the internet and it does

**Comment by leon0410898** [comment]
Why you need reinstall from the internet? Is it possible to install MacOS from USB?

**Comment by psanikos** [comment]
The installer from gibmacos just created the recovery partition so it has to download the rest from the internet... The previous time I did the same and worked without a problem but now for some reason it is not ...

**Comment by leon0410898** [comment]
You can download the whole installer from [gibmacos.](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os). No need to connect to the internet while in installation step.

**Comment by psanikos** [comment]
The installer log says nssoftlinking the sidecarui framework's library couldn't be loaded from (null)

Incompatible apps list timed out loading catalog
Predicate update product fetch failed with error error domain=com.apple.osinstallersetuo.error code=300 recovery server could not be contacted

**Comment by leon0410898** [comment]
I'm not sure why this happened. I've never met this problem before.

**Comment by psanikos** [comment]
I was hoping there was a fix for that because it's the only computer on the house and I would have to install windows again to start over 😅  I can't see the reason for this problem too i thought the date was wrong as some posts says but it's not...

**Comment by leon0410898** [comment]
Maybe this will help.
https://www.reddit.com/r/hackintosh/comments/hy1mv0/the_recovery_server_could_not_be_contacted/

**Comment by psanikos** [comment]
Thanks for your assistance I ll probably just start again this time with a full image and I hope where will not be an error again ..

**Comment by psanikos** [comment]
I ended up making a full installer and this time it worked but with the new EFI folder the wifi wasn't working ( made a sound like disconnecting just before showing the  sign in screen) so I used an earlier EFI folder you had posted a few days ago and now its working great

**Comment by leon0410898** [comment]
You can download latest [airportitlwm](https://github.com/OpenIntelWireless/itlwm/tags) (chose your macos version) if  wifi is not working
