### ISSUE TITLE
How to use native XPS 13 9300 Brightness ?? 

### ISSUE THREAD

**Issue by wzygadlo** [leon0410898/OC-XPS13-9300#9]
Is there a way to use native Dell screen brightness in OC ? 

At the moment XPS13 9300 has installed Catalina with OC, and I have noticed that max brightness is close to 60% of native dell brightness...

**Comment by leon0410898** [comment]
Almost all ice lake laptops have the same issue. I'll update the file if there is any solution.

**Comment by wzygadlo** [comment]
@leon0410898 can you tell me what has been done to fix the screen brightness is unusually low after sleep??

**Comment by leon0410898** [comment]
added [applebacklightsmoother.kext](https://github.com/hieplpvip/AppleBacklightSmoother)
